#!/bin/sh
# Verify that a basic git --version works correctly

# msf - change this to ZOSPM_TGT_ZFSROOT once dzip support in
runivp() {
	GIT_ROOT="${ZOSPM_SRC_ZFSROOT}rsusr/ported/bin"

	if ! [ -f "${GIT_ROOT}/git" ]; then
		echo "git configure failed. Expected ${GIT_ROOT} to exist and contain the 'git' tool" >&2
		return 8
	fi

	actual=`git --version`
	rc=$?
	if [ ${rc} != 0 ]; then
		echo "git --version return code was: $rc. Expected 0" >&2
		return 12
	fi
	expected='git version 2.14.4_zos_b09'
	if [ "${actual}" != "${expected}" ]; then
		echo "git --version returns unexpected output: ${actual} (Expected ${expected})" >&2
		return 16
	fi
}

out=$(whence zospmexternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zospmexternalfuncs
else    	
	echo "zospm tools need to be in your PATH" >&2
	exit 4
fi

mydir=$(callerdir ${0})
props="${mydir}/../../zospm/zospmglobalprops.json"
zospmpropse zospm config "${props}"

runivp
rc=$?
if [ $rc -gt 0 ]; then
	echo "IVP failed. Installation aborted"
	exit $rc
fi

exit 0
